# Generated by Django 4.1.3 on 2022-12-18 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_question_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='answer_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
