# Generated by Django 5.0 on 2024-02-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_answers_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('created_at',)},
        ),
    ]
